import React, { useState, useEffect } from 'react';
import { docketAPI, invoiceAPI } from '../utils/api'; // ✅ Import from api.js

export default function DocketForm() {
  const [formData, setFormData] = useState({
    eWayBill: '',
    partNo: '',
    itemDesc: '',
    invNo: '',
    weight: '0',
    packet: '0',
    invDate: '',
    netInvValue: '0',
    gInvValue: '0',
    docketNo: '',
    bookingDate: '',
    destinationCity: '',
    location: '',
    postalCode: '',
    expectedDelivery: '',
    customerType: 'Contractual Client',
    bookingMode: 'ROAD',
    origin: '',
    originCity: '',
    originLocation: '',
    destinationBranch: '',
    billingParty: '',
    billingAt: '',
    bookingType: 'To Pay',
    direction: 'DIRECT',
    deliveryMode: 'Door Delivery',
    loadType: 'PTL',
    gstinNo: '',
    isTemporaryConsignor: false,
    consignor: '',
    consignorAddress: '',
    consignorCity: '',
    consignorState: '',
    consignorPin: '',
    consignorPhone: '',
    crgstinNo: '',
    isTemporaryConsignee: true,
    consignee: '',
    consigneeAddress: '',
    consigneeCity: '',
    consigneeState: '',
    consigneePin: '',
    consigneePhone: '',
    cegstinNo: '',
  });

  const [dimensions, setDimensions] = useState([
    { id: 1, length: '0', width: '0', height: '0', noOfPackets: '0' }
  ]);

  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState('');
  const [isAutoGenerated, setIsAutoGenerated] = useState(true);

  // ✅ FIXED: Fetch next docket number on component mount
  useEffect(() => {
    fetchNextDocketNumber();
  }, []);

  // ✅ FIXED: Use axiosInstance instead of hardcoded fetch
  const fetchNextDocketNumber = async () => {
    try {
      const result = await docketAPI.getNextNumber(); // ✅ Use API from api.js
      
      if (result.success) {
        setFormData(prev => ({
          ...prev,
          docketNo: result.data.nextDocketNo
        }));
        setIsAutoGenerated(true);
      }
    } catch (error) {
      console.error('Error fetching next docket number:', error);
      setMessage('❌ Failed to fetch auto docket number');
    }
  };

  const handleInputChange = (e) => {
    const { name, value, type, checked } = e.target;
    
    if (name === 'docketNo') {
      setIsAutoGenerated(false);
    }
    
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }));
  };

  const handleDimensionChange = (id, field, value) => {
    setDimensions(prev =>
      prev.map(dim =>
        dim.id === id ? { ...dim, [field]: value } : dim
      )
    );
  };

  const addDimensionRow = () => {
    if (dimensions.length < 8) {
      const newId = dimensions.length > 0 ? Math.max(...dimensions.map(d => d.id)) + 1 : 1;
      setDimensions(prev => [...prev, { id: newId, length: '0', width: '0', height: '0', noOfPackets: '0' }]);
    }
  };

  const removeDimensionRow = (id) => {
    if (dimensions.length > 1) {
      setDimensions(prev => prev.filter(dim => dim.id !== id));
    }
  };

  // ✅ FIXED: Use invoiceAPI instead of hardcoded fetch
  const handleInvoiceSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setMessage('');

    try {
      const invoiceData = {
        eWayBill: formData.eWayBill,
        partNo: formData.partNo,
        itemDesc: formData.itemDesc,
        invNo: formData.invNo,
        weight: formData.weight,
        packet: formData.packet,
        invDate: formData.invDate,
        netInvValue: formData.netInvValue,
        gInvValue: formData.gInvValue,
      };

      const data = await invoiceAPI.create(invoiceData); // ✅ Use API from api.js

      if (data.success) {
        setMessage('✅ Invoice created successfully!');
      } else {
        setMessage(`❌ Error: ${data.message || 'Failed to create invoice'}`);
      }
    } catch (error) {
      setMessage(`❌ Error: ${error.response?.data?.message || error.message}`);
    } finally {
      setLoading(false);
    }
  };

  // ✅ FIXED: Use docketAPI instead of hardcoded fetch
  const handleDocketSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setMessage('');

    try {
      if (!formData.bookingDate) {
        setMessage('❌ Booking Date is required');
        setLoading(false);
        return;
      }

      if (!formData.destinationCity) {
        setMessage('❌ Destination City is required');
        setLoading(false);
        return;
      }

      const toISOString = (dateString) => {
        if (!dateString) return undefined;
        try {
          const date = new Date(dateString);
          if (isNaN(date.getTime())) {
            return undefined;
          }
          return date.toISOString();
        } catch (error) {
          console.error('Date conversion error:', error);
          return undefined;
        }
      };

      const docketData = {
        eWayBill: formData.eWayBill || undefined,
        partNo: formData.partNo || undefined,
        itemDesc: formData.itemDesc || undefined,
        invNo: formData.invNo || undefined,
        weight: parseFloat(formData.weight) || 0,
        packet: parseInt(formData.packet) || 0,
        invDate: toISOString(formData.invDate),
        netInvValue: parseFloat(formData.netInvValue) || 0,
        gInvValue: parseFloat(formData.gInvValue) || 0,
        docketNo: formData.docketNo || undefined,
        bookingDate: toISOString(formData.bookingDate),
        destinationCity: formData.destinationCity || undefined,
        location: formData.location || undefined,
        postalCode: formData.postalCode || undefined,
        expectedDelivery: toISOString(formData.expectedDelivery),
        customerType: formData.customerType || 'Contractual Client',
        bookingMode: formData.bookingMode || 'ROAD',
        origin: formData.origin || undefined,
        originCity: formData.originCity || undefined,
        originLocation: formData.originLocation || undefined,
        destinationBranch: formData.destinationBranch || undefined,
        billingParty: formData.billingParty || undefined,
        billingAt: formData.billingAt || undefined,
        bookingType: formData.bookingType || 'To Pay',
        direction: formData.direction || 'DIRECT',
        deliveryMode: formData.deliveryMode || 'Door Delivery',
        loadType: formData.loadType || 'PTL',
        gstinNo: formData.gstinNo || undefined,
        isTemporaryConsignor: formData.isTemporaryConsignor || false,
        consignor: formData.consignor || undefined,
        consignorAddress: formData.consignorAddress || undefined,
        consignorCity: formData.consignorCity || undefined,
        consignorState: formData.consignorState || undefined,
        consignorPin: formData.consignorPin || undefined,
        consignorPhone: formData.consignorPhone || undefined,
        crgstinNo: formData.crgstinNo || undefined,
        isTemporaryConsignee: formData.isTemporaryConsignee || true,
        consignee: formData.consignee || undefined,
        consigneeAddress: formData.consigneeAddress || undefined,
        consigneeCity: formData.consigneeCity || undefined,
        consigneeState: formData.consigneeState || undefined,
        consigneePin: formData.consigneePin || undefined,
        consigneePhone: formData.consigneePhone || undefined,
        cegstinNo: formData.cegstinNo || undefined,
        dimensions: dimensions.map(dim => ({
          length: parseFloat(dim.length) || 0,
          width: parseFloat(dim.width) || 0,
          height: parseFloat(dim.height) || 0,
          noOfPackets: parseInt(dim.noOfPackets) || 0,
        })),
      };

      const data = await docketAPI.create(docketData); // ✅ Use API from api.js

      if (data.success) {
        setMessage('✅ Docket created successfully!');
        // Optionally reset form
        setTimeout(() => {
          window.location.reload();
        }, 1500);
      } else {
        setMessage(`❌ Error: ${data.message || 'Failed to create docket'}`);
      }
    } catch (error) {
      setMessage(`❌ Error: ${error.response?.data?.message || error.message}`);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="p-6 bg-gray-50 min-h-screen">
      <h1 className="text-2xl font-bold mb-6 text-gray-800">Create New Docket</h1>
      
      {message && (
        <div className={`mb-4 p-4 rounded ${
          message.includes('✅') ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'
        }`}>
          {message}
        </div>
      )}

      <div className="bg-white rounded-lg shadow-md p-6">
        {/* Invoice Details Section */}
        <div className="mb-8">
          <h2 className="text-lg font-bold mb-4 text-gray-800 border-b pb-2">Invoice Details</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">E-Way Bill</label>
              <input
                type="text"
                name="eWayBill"
                value={formData.eWayBill}
                onChange={handleInputChange}
                className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Part No</label>
              <input
                type="text"
                name="partNo"
                value={formData.partNo}
                onChange={handleInputChange}
                className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Item Description</label>
              <input
                type="text"
                name="itemDesc"
                value={formData.itemDesc}
                onChange={handleInputChange}
                className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Invoice No</label>
              <input
                type="text"
                name="invNo"
                value={formData.invNo}
                onChange={handleInputChange}
                className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Weight</label>
              <input
                type="number"
                name="weight"
                value={formData.weight}
                onChange={handleInputChange}
                className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Packet</label>
              <input
                type="number"
                name="packet"
                value={formData.packet}
                onChange={handleInputChange}
                className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Invoice Date</label>
              <input
                type="date"
                name="invDate"
                value={formData.invDate}
                onChange={handleInputChange}
                className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Net Invoice Value</label>
              <input
                type="number"
                name="netInvValue"
                value={formData.netInvValue}
                onChange={handleInputChange}
                className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Gross Invoice Value</label>
              <input
                type="number"
                name="gInvValue"
                value={formData.gInvValue}
                onChange={handleInputChange}
                className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
              />
            </div>
          </div>
        </div>

        {/* Docket Details Section */}
        <div className="mb-8">
          <h2 className="text-lg font-bold mb-4 text-gray-800 border-b pb-2">Docket Details</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Docket No {isAutoGenerated && <span className="text-xs text-green-600">(Auto)</span>}
              </label>
              <input
                type="text"
                name="docketNo"
                value={formData.docketNo}
                onChange={handleInputChange}
                className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Booking Date *</label>
              <input
                type="date"
                name="bookingDate"
                value={formData.bookingDate}
                onChange={handleInputChange}
                required
                className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Destination City *</label>
              <input
                type="text"
                name="destinationCity"
                value={formData.destinationCity}
                onChange={handleInputChange}
                required
                className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Location</label>
              <input
                type="text"
                name="location"
                value={formData.location}
                onChange={handleInputChange}
                className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Postal Code</label>
              <input
                type="text"
                name="postalCode"
                value={formData.postalCode}
                onChange={handleInputChange}
                className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Expected Delivery</label>
              <input
                type="date"
                name="expectedDelivery"
                value={formData.expectedDelivery}
                onChange={handleInputChange}
                className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Customer Type</label>
              <select
                name="customerType"
                value={formData.customerType}
                onChange={handleInputChange}
                className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
              >
                <option>Contractual Client</option>
                <option>Cash Client</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Booking Mode</label>
              <select
                name="bookingMode"
                value={formData.bookingMode}
                onChange={handleInputChange}
                className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
              >
                <option>ROAD</option>
                <option>AIR</option>
                <option>RAIL</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Origin</label>
              <input
                type="text"
                name="origin"
                value={formData.origin}
                onChange={handleInputChange}
                className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Origin City</label>
              <input
                type="text"
                name="originCity"
                value={formData.originCity}
                onChange={handleInputChange}
                className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Origin Location</label>
              <input
                type="text"
                name="originLocation"
                value={formData.originLocation}
                onChange={handleInputChange}
                className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Destination Branch</label>
              <input
                type="text"
                name="destinationBranch"
                value={formData.destinationBranch}
                onChange={handleInputChange}
                className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Billing Party</label>
              <input
                type="text"
                name="billingParty"
                value={formData.billingParty}
                onChange={handleInputChange}
                className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Billing At</label>
              <input
                type="text"
                name="billingAt"
                value={formData.billingAt}
                onChange={handleInputChange}
                className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Booking Type</label>
              <select
                name="bookingType"
                value={formData.bookingType}
                onChange={handleInputChange}
                className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
              >
                <option>To Pay</option>
                <option>Paid</option>
                <option>To Be Billed</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Direction</label>
              <select
                name="direction"
                value={formData.direction}
                onChange={handleInputChange}
                className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
              >
                <option>DIRECT</option>
                <option>INDIRECT</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Delivery Mode</label>
              <select
                name="deliveryMode"
                value={formData.deliveryMode}
                onChange={handleInputChange}
                className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
              >
                <option>Door Delivery</option>
                <option>Godown Delivery</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Load Type</label>
              <select
                name="loadType"
                value={formData.loadType}
                onChange={handleInputChange}
                className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
              >
                <option>PTL</option>
                <option>FTL</option>
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">GSTIN No</label>
              <input
                type="text"
                name="gstinNo"
                value={formData.gstinNo}
                onChange={handleInputChange}
                className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
              />
            </div>
          </div>
        </div>

        {/* Consignor & Consignee */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-8">
          {/* Consignor Section */}
          <div className="border border-gray-300 p-4">
            <div className="flex items-center gap-2 mb-4">
              <input type="checkbox" name="isTemporaryConsignor" checked={formData.isTemporaryConsignor} onChange={handleInputChange} className="w-4 h-4" />
              <label className="font-bold text-sm text-gray-800">Is Temporary Consignor</label>
            </div>
            <div className="space-y-3">
              <div>
                <label className="text-xs font-medium text-gray-700">Consignor</label>
                <input type="text" name="consignor" value={formData.consignor} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" />
              </div>
              <div>
                <label className="text-xs font-medium text-gray-700">Address</label>
                <textarea name="consignorAddress" value={formData.consignorAddress} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1 h-16"></textarea>
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-xs font-medium text-gray-700">City</label>
                  <input type="text" name="consignorCity" value={formData.consignorCity} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" placeholder="Enter city" />
                </div>
                <div>
                  <label className="text-xs font-medium text-gray-700">Pin</label>
                  <input type="text" name="consignorPin" value={formData.consignorPin} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" />
                </div>
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-xs font-medium text-gray-700">State</label>
                  <input type="text" name="consignorState" value={formData.consignorState} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" placeholder="Enter state" />
                </div>
                <div>
                  <label className="text-xs font-medium text-gray-700">Phone</label>
                  <input type="text" name="consignorPhone" value={formData.consignorPhone} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" />
                </div>
              </div>
              <div>
                <label className="flex items-center gap-2 text-xs">
                  <input type="checkbox" className="w-4 h-4" />
                  <span className="font-medium text-gray-700">GSTIN No.</span>
                </label>
                <input type="text" name="crgstinNo" value={formData.crgstinNo} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" />
              </div>
            </div>
          </div>

          {/* Consignee Section */}
          <div className="border border-gray-300 p-4">
            <div className="flex items-center gap-2 mb-4">
              <input type="checkbox" name="isTemporaryConsignee" checked={formData.isTemporaryConsignee} onChange={handleInputChange} className="w-4 h-4" />
              <label className="font-bold text-sm text-gray-800">Is Temporary Consignee</label>
            </div>
            <div className="space-y-3">
              <div>
                <label className="text-xs font-medium text-gray-700">Consignee</label>
                <input type="text" name="consignee" value={formData.consignee} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" />
              </div>
              <div>
                <label className="text-xs font-medium text-gray-700">Address</label>
                <textarea name="consigneeAddress" value={formData.consigneeAddress} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1 h-16"></textarea>
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-xs font-medium text-gray-700">City</label>
                  <input type="text" name="consigneeCity" value={formData.consigneeCity} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" placeholder="Enter city" />
                </div>
                <div>
                  <label className="text-xs font-medium text-gray-700">Pin</label>
                  <input type="text" name="consigneePin" value={formData.consigneePin} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" />
                </div>
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-xs font-medium text-gray-700">State</label>
                  <input type="text" name="consigneeState" value={formData.consigneeState} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" placeholder="Enter state" />
                </div>
                <div>
                  <label className="text-xs font-medium text-gray-700">Phone</label>
                  <input type="text" name="consigneePhone" value={formData.consigneePhone} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" />
                </div>
              </div>
              <div>
                <label className="flex items-center gap-2 text-xs">
                  <input type="checkbox" className="w-4 h-4" />
                  <span className="font-medium text-gray-700">GSTIN No.</span>
                </label>
                <input type="text" name="cegstinNo" value={formData.cegstinNo} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" />
              </div>
            </div>
          </div>
        </div>

        {/* Dimensions Section */}
        <div className="border border-gray-300 p-4 mb-8">
          <div className="flex justify-between items-center mb-4">
            <h3 className="font-bold text-sm text-gray-800">Dimensions</h3>
            <button
              type="button"
              onClick={addDimensionRow}
              disabled={dimensions.length >= 8}
              className={`${
                dimensions.length >= 8 
                  ? 'bg-gray-400 cursor-not-allowed' 
                  : 'bg-green-600 hover:bg-green-700'
              } text-white font-bold px-4 py-1 rounded text-sm flex items-center gap-1`}
            >
              <span className="text-lg">+</span>
              Add Row
            </button>
          </div>

          <div className="space-y-3">
            {dimensions.map((dim, index) => (
              <div key={dim.id} className="grid grid-cols-5 gap-4 items-end pb-3 border-b border-gray-200">
                <div>
                  <label className="block text-xs font-medium text-gray-700 mb-1">
                    Length {index + 1}
                  </label>
                  <input 
                    type="number" 
                    value={dim.length}
                    onChange={(e) => handleDimensionChange(dim.id, 'length', e.target.value)}
                    placeholder="0"
                    className="w-full border border-gray-300 rounded px-2 py-1 text-sm" 
                  />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-700 mb-1">Width</label>
                  <input 
                    type="number" 
                    value={dim.width}
                    onChange={(e) => handleDimensionChange(dim.id, 'width', e.target.value)}
                    placeholder="0"
                    className="w-full border border-gray-300 rounded px-2 py-1 text-sm" 
                  />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-700 mb-1">Height</label>
                  <input 
                    type="number" 
                    value={dim.height}
                    onChange={(e) => handleDimensionChange(dim.id, 'height', e.target.value)}
                    placeholder="0"
                    className="w-full border border-gray-300 rounded px-2 py-1 text-sm" 
                  />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-700 mb-1">No. of Packets</label>
                  <input 
                    type="number" 
                    value={dim.noOfPackets}
                    onChange={(e) => handleDimensionChange(dim.id, 'noOfPackets', e.target.value)}
                    placeholder="0"
                    className="w-full border border-gray-300 rounded px-2 py-1 text-sm" 
                  />
                </div>
                <div>
                  {dimensions.length > 1 && (
                    <button
                      type="button"
                      onClick={() => removeDimensionRow(dim.id)}
                      className="bg-red-500 hover:bg-red-600 text-white px-3 py-1 rounded text-sm w-full"
                    >
                      Remove
                    </button>
                  )}
                </div>
              </div>
            ))}
          </div>

          <div className="mt-3 text-xs text-gray-600">
            {dimensions.length >= 8 ? (
              <span className="text-red-600 font-medium">Maximum 8 dimension rows reached</span>
            ) : (
              <span>Click "+ Add Row" to add more dimensions (max 8)</span>
            )}
          </div>
        </div>

        <div className="mt-6 flex gap-4 justify-end">
          <button
            onClick={handleDocketSubmit}
            disabled={loading}
            className="bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-6 rounded disabled:bg-gray-400 text-sm"
          >
            {loading ? 'SAVING...' : 'SAVE DOCKET'}
          </button>
        </div>
      </div>
    </div>
  );
}