import React, { useState, useEffect } from 'react';
import { docketAPI, invoiceAPI } from '../utils/api';

export default function DocketForm() {
  const [formData, setFormData] = useState({
    eWayBill: '',
    partNo: '',
    itemDesc: '',
    invNo: '',
    weight: '0',
    packet: '0',
    invDate: '',
    netInvValue: '0',
    gInvValue: '0',
    docketNo: '',
    bookingDate: '',
    destinationCity: '',
    postalCode: '',
    expectedDelivery: '',
    customerType: 'Contractual Client',
    bookingMode: 'ROAD',
    originCity: '',
    billingParty: '',
    billingAt: '',
    bookingType: 'To Pay',
    deliveryMode: 'Door Delivery',
    loadType: 'PTL',
    gstinNo: '',
    isTemporaryConsignor: false,
    consignor: '',
    consignorAddress: '',
    consignorCity: '',
    consignorState: '',
    consignorPin: '',
    consignorPhone: '',
    crgstinNo: '',
    isTemporaryConsignee: true,
    consignee: '',
    consigneeAddress: '',
    consigneeCity: '',
    consigneeState: '',
    consigneePin: '',
    consigneePhone: '',
    cegstinNo: '',
  });

  // Dimensions array state - starts with one row
  const [dimensions, setDimensions] = useState([
    { id: 1, length: '0', width: '0', height: '0', noOfPackets: '0' }
  ]);

  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState('');
  const [isAutoGenerated, setIsAutoGenerated] = useState(true); // ✅ NEW: Track if using auto number

  // ✅ NEW: Fetch next docket number on component mount
  useEffect(() => {
    fetchNextDocketNumber();
  }, []);

  const fetchNextDocketNumber = async () => {
    try {
      const result = await docketAPI.getNextNumber();
      
      if (result.success) {
        setFormData(prev => ({
          ...prev,
          docketNo: result.data.nextDocketNo
        }));
        setIsAutoGenerated(true);
      }
    } catch (error) {
      console.error('Error fetching next docket number:', error);
      setMessage('❌ Failed to fetch auto docket number');
    }
  };

  const handleInputChange = (e) => {
    const { name, value, type, checked } = e.target;
    
    // ✅ NEW: If user manually changes docket number, mark as not auto-generated
    if (name === 'docketNo') {
      setIsAutoGenerated(false);
    }
    
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? checked : value
    }));
  };

  // Handle dimension row changes
  const handleDimensionChange = (id, field, value) => {
    setDimensions(prev =>
      prev.map(dim =>
        dim.id === id ? { ...dim, [field]: value } : dim
      )
    );
  };

  // Add new dimension row (max 8)
  const addDimensionRow = () => {
    if (dimensions.length < 8) {
      const newId = dimensions.length > 0 ? Math.max(...dimensions.map(d => d.id)) + 1 : 1;
      setDimensions(prev => [...prev, { id: newId, length: '0', width: '0', height: '0', noOfPackets: '0' }]);
    }
  };

  // Remove dimension row
  const removeDimensionRow = (id) => {
    if (dimensions.length > 1) {
      setDimensions(prev => prev.filter(dim => dim.id !== id));
    }
  };

  const handleInvoiceSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setMessage('');

    try {
      const invoiceData = {
        eWayBill: formData.eWayBill,
        partNo: formData.partNo,
        itemDesc: formData.itemDesc,
        invNo: formData.invNo,
        weight: formData.weight,
        packet: formData.packet,
        invDate: formData.invDate,
        netInvValue: formData.netInvValue,
        gInvValue: formData.gInvValue,
      };

      const data = await invoiceAPI.create(invoiceData);

      if (data.success) {
        setMessage('✅ Invoice created successfully!');
      } else {
        setMessage(`❌ Error: ${data.message || 'Failed to create invoice'}`);
      }
    } catch (error) {
      setMessage(`❌ Error: ${error.response?.data?.message || error.message}`);
    } finally {
      setLoading(false);
    }
  };

  const handleDocketSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setMessage('');

    try {
      // Validate required fields before submission
      if (!formData.bookingDate) {
        setMessage('❌ Booking Date is required');
        setLoading(false);
        return;
      }

      if (!formData.destinationCity) {
        setMessage('❌ Destination City is required');
        setLoading(false);
        return;
      }

      // Helper function to safely convert date to ISO string
      const toISOString = (dateString) => {
        if (!dateString) return undefined; // Don't include field if empty
        try {
          const date = new Date(dateString);
          if (isNaN(date.getTime())) {
            return undefined;
          }
          return date.toISOString();
        } catch (error) {
          console.error('Date conversion error:', error);
          return undefined;
        }
      };

      // Prepare docket data with dimensions array and isAutoGenerated flag
      const docketData = {
        ...formData,
        // Convert date strings to ISO format for proper backend handling
        bookingDate: toISOString(formData.bookingDate), // This will always have a value due to validation above
        expectedDelivery: toISOString(formData.expectedDelivery),
        invDate: toISOString(formData.invDate),
        dimensions: dimensions, // Send all dimension rows
        isAutoGenerated: isAutoGenerated // ✅ NEW: Send the flag
      };

      // Remove undefined values to prevent sending them to backend
      Object.keys(docketData).forEach(key => {
        if (docketData[key] === undefined) {
          delete docketData[key];
        }
      });

      console.log('Submitting docket data:', docketData); // Debug log

      const data = await docketAPI.create(docketData);

      if (data.success) {
        setMessage('✅ Docket created successfully!');
        
        // ✅ NEW: Reset form and fetch next docket number
        setTimeout(() => {
          // Reset form data
          setFormData({
            eWayBill: '',
            partNo: '',
            itemDesc: '',
            invNo: '',
            weight: '0',
            packet: '0',
            invDate: '',
            netInvValue: '0',
            gInvValue: '0',
            docketNo: '',
            bookingDate: '',
            destinationCity: '',
            postalCode: '',
            expectedDelivery: '',
            customerType: 'Contractual Client',
            bookingMode: 'ROAD',
            originCity: '',
            billingParty: '',
            billingAt: '',
            bookingType: 'To Pay',
            deliveryMode: 'Door Delivery',
            loadType: 'PTL',
            gstinNo: '',
            isTemporaryConsignor: false,
            consignor: '',
            consignorAddress: '',
            consignorCity: '',
            consignorState: '',
            consignorPin: '',
            consignorPhone: '',
            crgstinNo: '',
            isTemporaryConsignee: true,
            consignee: '',
            consigneeAddress: '',
            consigneeCity: '',
            consigneeState: '',
            consigneePin: '',
            consigneePhone: '',
            cegstinNo: '',
          });
          
          // Reset dimensions
          setDimensions([{ id: 1, length: '0', width: '0', height: '0', noOfPackets: '0' }]);
          
          // Fetch next auto number
          fetchNextDocketNumber();
          
          setMessage('');
        }, 2000);
      } else {
        setMessage(`❌ Error: ${data.message || 'Failed to create docket'}`);
      }
    } catch (error) {
      setMessage(`❌ Error: ${error.response?.data?.message || error.message}`);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-100 p-6">
      <div className="max-w-7xl mx-auto bg-white rounded p-6">
        
        {/* Message */}
        {message && (
          <div className={`mb-4 p-3 rounded ${message.includes('✅') ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'}`}>
            {message}
          </div>
        )}

        {/* Invoice Details Section */}
        <div className="mb-8">
          <div className="flex justify-between items-center mb-4">
            <h2 className="text-sm font-bold text-gray-800">Invoice Details ☑</h2>
            <button
              onClick={handleInvoiceSubmit}
              disabled={loading}
              className="bg-blue-600 hover:bg-blue-700 text-white font-bold py-1 px-4 rounded text-sm disabled:bg-gray-400"
            >
              + {loading ? 'SAVING...' : 'ADD INVOICE'}
            </button>
          </div>
          
          <div className="border border-gray-300 p-4">
            <div className="grid grid-cols-12 gap-3 mb-4">
              <div className="col-span-2">
                <label className="block text-xs font-medium text-gray-700 mb-1">E-WayBill</label>
                <input type="text" name="eWayBill" value={formData.eWayBill} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm" />
              </div>
              <div className="col-span-2">
                <label className="block text-xs font-medium text-gray-700 mb-1">Inv. No.</label>
                <input type="text" name="invNo" value={formData.invNo} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm" />
              </div>
              <div className="col-span-2">
                <label className="block text-xs font-medium text-gray-700 mb-1">Inv. Date</label>
                <input type="date" name="invDate" value={formData.invDate} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm" />
              </div>
              <div className="col-span-2">
                <label className="block text-xs font-medium text-gray-700 mb-1">Net Inv Value</label>
                <input type="text" name="netInvValue" value={formData.netInvValue} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm" />
              </div>
              <div className="col-span-2">
                <label className="block text-xs font-medium text-gray-700 mb-1">G Inv Value</label>
                <input type="text" name="gInvValue" value={formData.gInvValue} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm" />
              </div>
              <div className="col-span-2">
                <label className="block text-xs font-medium text-gray-700 mb-1">Part No.</label>
                <input type="text" name="partNo" value={formData.partNo} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm" />
              </div>
            </div>
            <div className="mb-4">
              <label className="block text-xs font-medium text-gray-700 mb-1">Item Description</label>
              <textarea name="itemDesc" value={formData.itemDesc} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm h-20"></textarea>
            </div>
            <div className="grid grid-cols-2 gap-3">
              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">Weight</label>
                <input type="text" name="weight" value={formData.weight} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm" />
              </div>
              <div>
                <label className="block text-xs font-medium text-gray-700 mb-1">Packet</label>
                <input type="text" name="packet" value={formData.packet} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm" />
              </div>
            </div>
          </div>
        </div>

        {/* Three Column Docket Info */}
        <div className="grid grid-cols-3 gap-4 mb-8">
          
          {/* Left Column - Docket & Destination */}
          <div className="border border-gray-300 p-4">
            <h3 className="font-bold text-sm text-gray-800 mb-3">Docket Info</h3>
            <div className="space-y-3">
              {/* ✅ UPDATED: Docket No with auto-indicator */}
              <div>
                <label className="text-xs font-medium text-gray-700 flex items-center justify-between">
                  <span>Docket No.</span>
                  {isAutoGenerated && (
                    <span className="text-[10px] bg-green-100 text-green-700 px-2 py-0.5 rounded">AUTO</span>
                  )}
                </label>
                <input 
                  type="text" 
                  name="docketNo" 
                  value={formData.docketNo} 
                  onChange={handleInputChange} 
                  className={`w-full border ${isAutoGenerated ? 'border-green-300 bg-green-50' : 'border-gray-300'} rounded px-2 py-1 text-sm mt-1`}
                  placeholder="053221"
                />
              </div>
              <div>
                <label className="text-xs font-medium text-gray-700">Booking Date</label>
                <input type="date" name="bookingDate" value={formData.bookingDate} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" />
              </div>
              <div>
                <label className="text-xs font-medium text-gray-700">Destination/City</label>
                <input type="text" name="destinationCity" value={formData.destinationCity} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" />
              </div>
              <div>
                <label className="text-xs font-medium text-gray-700">Postal Code</label>
                <input type="text" name="postalCode" value={formData.postalCode} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" />
              </div>
              <div>
                <label className="text-xs font-medium text-gray-700">Expected Delivery</label>
                <input type="date" name="expectedDelivery" value={formData.expectedDelivery} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" />
              </div>
            </div>
          </div>

          {/* Middle Column - Booking Details */}
          <div className="border border-gray-300 p-4">
            <h3 className="font-bold text-sm text-gray-800 mb-3">Booking Details</h3>
            <div className="space-y-3">
              <div>
                <label className="text-xs font-medium text-gray-700">Customer Type</label>
                <select name="customerType" value={formData.customerType} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1">
                  <option value="Contractual Client">Contractual Client</option>
                </select>
              </div>
              <div>
                <label className="text-xs font-medium text-gray-700">Booking Mode</label>
                <select name="bookingMode" value={formData.bookingMode} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1">
                  <option value="ROAD">ROAD</option>
                  <option value="AIR">AIR</option>
                  <option value="RAIL">RAIL</option>
                  <option value="SEA">SEA</option>
                </select>
              </div>
              <div>
                <label className="text-xs font-medium text-gray-700">Origin City</label>
                <input type="text" name="originCity" value={formData.originCity} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" placeholder="Enter city name" />
              </div>
            </div>
          </div>

          {/* Right Column - Billing Details */}
          <div className="border border-gray-300 p-4">
            <h3 className="font-bold text-sm text-gray-800 mb-3">Billing Details</h3>
            <div className="space-y-3">
              <div>
                <label className="text-xs font-medium text-gray-700">Billing Party</label>
                <input type="text" name="billingParty" value={formData.billingParty} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" />
              </div>
              <div>
                <label className="text-xs font-medium text-gray-700">Billing At</label>
                <input type="text" name="billingAt" value={formData.billingAt} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" />
              </div>
              <div>
                <label className="text-xs font-medium text-gray-700">Booking Type</label>
                <select name="bookingType" value={formData.bookingType} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1">
                  <option value="To Pay">To Pay</option>
                  <option value="Paid">Paid</option>
                  <option value="Credit">Credit</option>
                </select>
              </div>
              <div>
                <label className="text-xs font-medium text-gray-700">Delivery Mode</label>
                <select name="deliveryMode" value={formData.deliveryMode} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1">
                  <option value="Door Delivery">Door Delivery</option>
                  <option value="Godown Delivery">Godown Delivery</option>
                </select>
              </div>
              <div>
                <label className="text-xs font-medium text-gray-700">Load Type</label>
                <select name="loadType" value={formData.loadType} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1">
                  <option value="PTL">PTL</option>
                  <option value="FTL">FTL</option>
                </select>
              </div>
              <div>
                <label className="text-xs font-medium text-gray-700">GSTIN No.</label>
                <input type="text" name="gstinNo" value={formData.gstinNo} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" />
              </div>
            </div>
          </div>
        </div>

        {/* Consignor and Consignee - Two Column */}
        <div className="grid grid-cols-2 gap-4 mb-8">
          
          {/* Consignor Section */}
          <div className="border border-gray-300 p-4">
            <div className="flex items-center gap-2 mb-4">
              <input type="checkbox" name="isTemporaryConsignor" checked={formData.isTemporaryConsignor} onChange={handleInputChange} className="w-4 h-4" />
              <label className="font-bold text-sm text-gray-800">Is Temporary Consignor</label>
            </div>
            <div className="space-y-3">
              <div>
                <label className="text-xs font-medium text-gray-700">Consignor</label>
                <input type="text" name="consignor" value={formData.consignor} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" />
              </div>
              <div>
                <label className="text-xs font-medium text-gray-700">Address</label>
                <textarea name="consignorAddress" value={formData.consignorAddress} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1 h-16"></textarea>
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-xs font-medium text-gray-700">City</label>
                  <input type="text" name="consignorCity" value={formData.consignorCity} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" placeholder="Enter city" />
                </div>
                <div>
                  <label className="text-xs font-medium text-gray-700">Pin</label>
                  <input type="text" name="consignorPin" value={formData.consignorPin} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" />
                </div>
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-xs font-medium text-gray-700">State</label>
                  <input type="text" name="consignorState" value={formData.consignorState} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" placeholder="Enter state" />
                </div>
                <div>
                  <label className="text-xs font-medium text-gray-700">Phone</label>
                  <input type="text" name="consignorPhone" value={formData.consignorPhone} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" />
                </div>
              </div>
              <div>
                <label className="flex items-center gap-2 text-xs">
                  <input type="checkbox" className="w-4 h-4" />
                  <span className="font-medium text-gray-700">GSTIN No.</span>
                </label>
                <input type="text" name="crgstinNo" value={formData.crgstinNo} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" />
              </div>
            </div>
          </div>

          {/* Consignee Section */}
          <div className="border border-gray-300 p-4">
            <div className="flex items-center gap-2 mb-4">
              <input type="checkbox" name="isTemporaryConsignee" checked={formData.isTemporaryConsignee} onChange={handleInputChange} className="w-4 h-4" />
              <label className="font-bold text-sm text-gray-800">Is Temporary Consignee</label>
            </div>
            <div className="space-y-3">
              <div>
                <label className="text-xs font-medium text-gray-700">Consignee</label>
                <input type="text" name="consignee" value={formData.consignee} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" />
              </div>
              <div>
                <label className="text-xs font-medium text-gray-700">Address</label>
                <textarea name="consigneeAddress" value={formData.consigneeAddress} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1 h-16"></textarea>
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-xs font-medium text-gray-700">City</label>
                  <input type="text" name="consigneeCity" value={formData.consigneeCity} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" placeholder="Enter city" />
                </div>
                <div>
                  <label className="text-xs font-medium text-gray-700">Pin</label>
                  <input type="text" name="consigneePin" value={formData.consigneePin} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" />
                </div>
              </div>
              <div className="grid grid-cols-2 gap-3">
                <div>
                  <label className="text-xs font-medium text-gray-700">State</label>
                  <input type="text" name="consigneeState" value={formData.consigneeState} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" placeholder="Enter state" />
                </div>
                <div>
                  <label className="text-xs font-medium text-gray-700">Phone</label>
                  <input type="text" name="consigneePhone" value={formData.consigneePhone} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" />
                </div>
              </div>
              <div>
                <label className="flex items-center gap-2 text-xs">
                  <input type="checkbox" className="w-4 h-4" />
                  <span className="font-medium text-gray-700">GSTIN No.</span>
                </label>
                <input type="text" name="cegstinNo" value={formData.cegstinNo} onChange={handleInputChange} className="w-full border border-gray-300 rounded px-2 py-1 text-sm mt-1" />
              </div>
            </div>
          </div>
        </div>

        {/* ================= DYNAMIC DIMENSIONS SECTION ================= */}
        <div className="border border-gray-300 p-4 mb-8">
          <div className="flex justify-between items-center mb-4">
            <h3 className="font-bold text-sm text-gray-800">Dimensions</h3>
            <button
              type="button"
              onClick={addDimensionRow}
              disabled={dimensions.length >= 8}
              className={`${
                dimensions.length >= 8 
                  ? 'bg-gray-400 cursor-not-allowed' 
                  : 'bg-green-600 hover:bg-green-700'
              } text-white font-bold px-4 py-1 rounded text-sm flex items-center gap-1`}
            >
              <span className="text-lg">+</span>
              Add Row
            </button>
          </div>

          {/* Dimension Rows */}
          <div className="space-y-3">
            {dimensions.map((dim, index) => (
              <div key={dim.id} className="grid grid-cols-5 gap-4 items-end pb-3 border-b border-gray-200">
                <div>
                  <label className="block text-xs font-medium text-gray-700 mb-1">
                    Length {index + 1}
                  </label>
                  <input 
                    type="number" 
                    value={dim.length}
                    onChange={(e) => handleDimensionChange(dim.id, 'length', e.target.value)}
                    placeholder="0"
                    className="w-full border border-gray-300 rounded px-2 py-1 text-sm" 
                  />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-700 mb-1">Width</label>
                  <input 
                    type="number" 
                    value={dim.width}
                    onChange={(e) => handleDimensionChange(dim.id, 'width', e.target.value)}
                    placeholder="0"
                    className="w-full border border-gray-300 rounded px-2 py-1 text-sm" 
                  />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-700 mb-1">Height</label>
                  <input 
                    type="number" 
                    value={dim.height}
                    onChange={(e) => handleDimensionChange(dim.id, 'height', e.target.value)}
                    placeholder="0"
                    className="w-full border border-gray-300 rounded px-2 py-1 text-sm" 
                  />
                </div>
                <div>
                  <label className="block text-xs font-medium text-gray-700 mb-1">No. of Packets</label>
                  <input 
                    type="number" 
                    value={dim.noOfPackets}
                    onChange={(e) => handleDimensionChange(dim.id, 'noOfPackets', e.target.value)}
                    placeholder="0"
                    className="w-full border border-gray-300 rounded px-2 py-1 text-sm" 
                  />
                </div>
                <div>
                  {dimensions.length > 1 && (
                    <button
                      type="button"
                      onClick={() => removeDimensionRow(dim.id)}
                      className="bg-red-500 hover:bg-red-600 text-white px-3 py-1 rounded text-sm w-full"
                    >
                      Remove
                    </button>
                  )}
                </div>
              </div>
            ))}
          </div>

          {/* Info text */}
          <div className="mt-3 text-xs text-gray-600">
            {dimensions.length >= 8 ? (
              <span className="text-red-600 font-medium">Maximum 8 dimension rows reached</span>
            ) : (
              <span>Click "+ Add Row" to add more dimensions (max 8)</span>
            )}
          </div>
        </div>

        <div className="mt-6 flex gap-4 justify-end">
          <button
            onClick={handleDocketSubmit}
            disabled={loading}
            className="bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-6 rounded disabled:bg-gray-400 text-sm"
          >
            {loading ? 'SAVING...' : 'SAVE DOCKET'}
          </button>
        </div>
      </div>
    </div>
  );
}