import mongoose from "mongoose";

const docketSchema = new mongoose.Schema(
  {
    docketNo: { type: String, required: true },
    bookingDate: { type: Date, required: true },
    destinationCity: { type: String, required: true },
    postalCode: { type: String },
    expectedDelivery: { type: Date },
    
    // Consignor and Consignee references
    consignor: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Consignor",
    },
    consignee: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Consignee",
    },
    
    // Dimensions array
    dimensions: [{
      length: { type: Number, default: 0 },
      width:  { type: Number, default: 0 },
      height: { type: Number, default: 0 },
      noOfPackets: { type: Number, default: 0 },
    }],
    
    // Auto-generated tracking
    isAutoGenerated: { type: Boolean, default: true },
    
    // Distance for E-way Bill
    distance: { type: Number, default: 0 },
    
    // Docket Status & Cancellation Fields
    docketStatus: {
      type: String,
      enum: ['Active', 'Cancelled', 'Completed'],
      default: 'Active'
    },
    
    cancelledAt:        { type: Date,   default: null },
    cancelledBy:        { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },
    cancellationReason: { type: String, default: '' },
    
    // RTO (Return to Origin) field
    rto: { type: Boolean, default: false },
    
    // Co-Loader flag
    coLoader: { type: Boolean, default: false, index: true },

    // MIS Receipt — ImgBB upload
    misImageUrl:    { type: String, default: null },  // ImgBB display URL
    misImageDeleteHash: { type: String, default: null },  // ImgBB delete hash (for future deletion)

  },
  { timestamps: true }
);

export default mongoose.model("Docket", docketSchema);