import mongoose from "mongoose";

const docketSchema = new mongoose.Schema(
  {
    docketNo: { type: String, required: true },
    bookingDate: { type: Date, required: true },
    destinationCity: { type: String, required: true },
    location: { type: String },
    postalCode: { type: String },
    expectedDelivery: { type: Date },
    // IMPORTANT: Add these two fields to link Docket to Consignor and Consignee
    consignor: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Consignor",
    },
    consignee: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Consignee",
    },
    // ✅ UPDATED: Dimensions field now accepts an array (up to 8 rows)
    dimensions: [{
      length: {
        type: Number,
        default: 0,
      },
      width: {
        type: Number,
        default: 0,
      },
      height: {
        type: Number,
        default: 0,
      },
      noOfPackets: {
        type: Number,
        default: 0,
      },
    }],
    // ✅ NEW: Track if docket number was auto-generated
    isAutoGenerated: {
      type: Boolean,
      default: true
    },
    // ✅ NEW: Store distance for E-way Bill expiry calculation
    distance: {
      type: Number,
      default: 0, // Distance in KM between origin and destination
    }
  },
  { timestamps: true }
);

export default mongoose.model("Docket", docketSchema);